version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres,postgres_test
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  setup:
    image: postgres
    container_name: postgres-setup
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: postgres,postgres_test

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solva
    depends_on:
      - setup
    volumes:
      - ./target/solva.jar:/app/solva.jar
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    command: ["java", "-jar", "solva.jar"]
